---

- name: Install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - chromium-browser
    - powertop
    - tlp
    - tlp-rdw

- name: Make sure services are started
  become: true
  service:
    name: tlp
    state: started

- name: Create a directory to put all the codes
  file:
    path: "{{ lookup('env', 'HOME') }}/code"
    state: directory
