---

- name: Install packages
  become: true
  apt: name="{{item}}" state=present
  with_items:
    - chromium-browser
    - powertop
    - tlp
    - tlp-rdw
    - vim
    - nodejs
    - nodejs-legacy
    - npm

- name: Make sure services are started
  become: true
  service:
    name: tlp
    state: started

- name: Create a directory to put all the codes
  file:
    path: "{{ lookup('env', 'HOME') }}/code"
    state: directory

- name: Install some node.js packages globally
  become: true
  npm:
    name: karma-cli
    global: yes
