---

- name: Install common packages
  become: true
  package:
    name: "{{ common_packages }}"
    state: present

- name: Include distro specific vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install distro specific packages
  become: true
  package:
    name: "{{ distro_packages }}"
    state: present

- name: Make sure services are started
  become: true
  service:
    name: tlp
    state: started
